---
# tasks file for rng-tools
- name: Install rng-tools - AlmaLinux
  ansible.builtin.dnf:
    name: "rng-tools"
    state: latest
  when: ansible_distribution == 'AlmaLinux'

- name: Start rngd - AlmaLinux
  ansible.builtin.service:
    name: rngd
    state: started
    enabled: yes