---
# tasks file for chrony
- name: Install chrony - AlmaLinux
  ansible.builtin.dnf:
    name: "chrony"
    state: latest
  when: ansible_distribution == 'AlmaLinux'

- name: Install chrony.conf file
  ansible.builtin.copy:
    src: chrony.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644

- name: Start Chrony - AlmaLinux
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: yes