- name: Install Chromium and remove Firefox ESR
  hosts: local
  connection: local
  become: true
  tasks:
    - name: Ensure Chromium is installed
      ansible.builtin.apt:
        name: chromium
        state: present
        update_cache: true
        cache_valid_time: 3600
      tags: ['pkg', 'chromium']

    - name: Ensure Firefox ESR is removed
      ansible.builtin.apt:
        name: firefox-esr
        state: absent
        update_cache: true
        cache_valid_time: 3600
      tags: ['pkg', 'firefox']
