- name: Set up SSH authorized key for local user
  hosts: local
  connection: local
  vars:
    local_user: "{{ ansible_env.USER }}"
    ssh_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICEAwMkiwPc3Cq3qpewo3PAc6DhvG1uizTEuDVJ9oA9u"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOy4aWIgXtp93VlEefKAM+Qswa2K9eg3HgrIKpssCr7Z jeremy@Jeremys-MacBook-Air.local"
  tasks:
    - name: Set up SSH authorized key # trunk-ignore(ansible-lint/syntax-check)
      ansible.posix.authorized_key:
        user: "{{ local_user }}"
        key: "{{ item }}"
      loop: "{{ ssh_keys }}"
