- name: Set up SSH authorized key for local user
  hosts: local
  connection: local
  vars:
    local_user: "{{ ansible_env.USER }}"

  tasks:
    - name: Set up SSH authorized key # trunk-ignore(ansible-lint/syntax-check)
      ansible.posix.authorized_key:
        user: "{{ local_user }}"
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICEAwMkiwPc3Cq3qpewo3PAc6DhvG1uizTEuDVJ9oA9u"
